class_name SoundBank
extends RefCounted
## Sound ids → files. Ids with several variants ("hit") pick one at random so
## repeated sounds don't fatigue. Files live in assets/audio/ and are
## generated by tools/audio/synth_audio.py (swap in real recordings any time:
## keep the file names, or edit the tables below).

const SFX_DIR := "res://assets/audio/sfx/"
const MUSIC_DIR := "res://assets/audio/music/"
const AMBIENCE_DIR := "res://assets/audio/ambience/"

## id -> list of file base names (variants).
const SFX := {
	&"ui_hover": ["ui_hover"], &"ui_click": ["ui_click"], &"ui_back": ["ui_back"],
	&"card_draw": ["card_draw_1", "card_draw_2", "card_draw_3"], &"card_hover": ["card_hover"],
	&"card_play": ["card_play"], &"card_discard": ["card_discard"], &"card_exhaust": ["card_exhaust"],
	&"card_create": ["card_create"], &"shuffle": ["shuffle"],
	&"hit": ["hit_1", "hit_2", "hit_3"], &"hit_heavy": ["hit_heavy"],
	&"block_gain": ["block_gain"], &"block_break": ["block_break"], &"enemy_windup": ["enemy_windup"],
	&"poison_tick": ["poison_tick"], &"burn_tick": ["burn_tick"],
	&"status_buff": ["status_buff"], &"status_debuff": ["status_debuff"], &"heal": ["heal"], &"death": ["death"],
	&"energy": ["energy"], &"overheat": ["overheat"], &"stoke": ["stoke"],
	&"stance_wax": ["stance_wax"], &"stance_wane": ["stance_wane"], &"eclipse": ["eclipse"], &"summon": ["summon"],
	&"gold": ["gold"], &"relic": ["relic"], &"potion": ["potion"], &"map_select": ["map_select"], &"rest": ["rest"],
	&"shop_buy": ["shop_buy"], &"turn_player": ["turn_player"], &"turn_enemy": ["turn_enemy"],
	&"boss_intro": ["boss_intro"], &"victory": ["victory"], &"defeat": ["defeat"],
	&"motif_pyre_warden": ["motif_warden"], &"motif_moonblade": ["motif_moonblade"],
}

## Relative loudness per id (dB), so the mix doesn't need tuning at call sites.
const GAIN_DB := {
	&"ui_hover": -14.0, &"ui_click": -8.0, &"card_hover": -16.0, &"card_draw": -12.0, &"card_discard": -12.0,
	&"shuffle": -8.0, &"energy": -10.0, &"turn_player": -6.0, &"turn_enemy": -6.0, &"stoke": -8.0,
	&"poison_tick": -6.0, &"burn_tick": -6.0, &"status_buff": -6.0, &"status_debuff": -6.0,
	&"block_gain": -4.0, &"map_select": -4.0, &"victory": -4.0, &"motif_pyre_warden": -3.0, &"motif_moonblade": -3.0,
}

const MUSIC := {
	&"menu": "menu", &"map_act1": "map_act1", &"map_act2": "map_act2",
	&"combat": "combat", &"elite": "elite", &"boss": "boss",
}

const AMBIENCE := {&"swamp": "swamp", &"crypt": "crypt"}

static var _cache: Dictionary = {}


static func sfx(id: StringName) -> AudioStream:
	var variants: Array = SFX.get(id, [])
	if variants.is_empty():
		return null
	return _load(SFX_DIR + String(variants.pick_random()) + ".ogg", false)


static func gain_db(id: StringName) -> float:
	return GAIN_DB.get(id, 0.0)


static func music(id: StringName) -> AudioStream:
	return _load(MUSIC_DIR + String(MUSIC.get(id, "")) + ".ogg", true) if MUSIC.has(id) else null


static func ambience(id: StringName) -> AudioStream:
	return _load(AMBIENCE_DIR + String(AMBIENCE.get(id, "")) + ".ogg", true) if AMBIENCE.has(id) else null


static func _load(path: String, looping: bool) -> AudioStream:
	if _cache.has(path):
		return _cache[path]
	if not ResourceLoader.exists(path):
		push_warning("SoundBank: missing %s" % path)
		_cache[path] = null
		return null
	var stream: AudioStream = load(path)
	if looping and stream is AudioStreamOggVorbis:
		stream.loop = true
	_cache[path] = stream
	return stream


static func clear_cache() -> void:
	_cache.clear()
